SCHEMA_PREFIX = "nswdesignsystem"
CONTROL_PANEL_TITLE = "NSW Design System Settings"
COLOUR_PALETTE = [
    {"name": "grey-01", "label": "Grey 01"},
    {"name": "green-01", "label": "Green 01"},
    {"name": "teal-01", "label": "Teal 01"},
    {"name": "blue-01", "label": "Blue 01"},
    {"name": "purple-01", "label": "Purple 01"},
    {"name": "pink-01", "label": "Pink 01"},
    {"name": "red-01", "label": "Red 01"},
    {"name": "orange-01", "label": "Orange 01"},
    {"name": "yellow-01", "label": "Yellow 01"},
    {"name": "brown-01", "label": "Brown 01"},
    {"name": "grey-02", "label": "Grey 02"},
    {"name": "green-02", "label": "Green 02"},
    {"name": "teal-02", "label": "Teal 02"},
    {"name": "blue-02", "label": "Blue 02"},
    {"name": "purple-02", "label": "Purple 02"},
    {"name": "pink-02", "label": "Pink 02"},
    {"name": "red-02", "label": "Red 02"},
    {"name": "orange-02", "label": "Orange 02"},
    {"name": "yellow-02", "label": "Yellow 02"},
    {"name": "brown-02", "label": "Brown 02"},
    {"name": "grey-03", "label": "Grey 03"},
    {"name": "green-03", "label": "Green 03"},
    {"name": "teal-03", "label": "Teal 03"},
    {"name": "blue-03", "label": "Blue 03"},
    {"name": "purple-03", "label": "Purple 03"},
    {"name": "pink-03", "label": "Pink 03"},
    {"name": "red-03", "label": "Red 03"},
    {"name": "orange-03", "label": "Orange 03"},
    {"name": "yellow-03", "label": "Yellow 03"},
    {"name": "brown-03", "label": "Brown 03"},
    {"name": "grey-04", "label": "Grey 04"},
    {"name": "green-04", "label": "Green 04"},
    {"name": "teal-04", "label": "Teal 04"},
    {"name": "blue-04", "label": "Blue 04"},
    {"name": "purple-04", "label": "Purple 04"},
    {"name": "pink-04", "label": "Pink 04"},
    {"name": "red-04", "label": "Red 04"},
    {"name": "orange-04", "label": "Orange 04"},
    {"name": "yellow-04", "label": "Yellow 04"},
    {"name": "brown-04", "label": "Brown 04"},
    {"name": "black", "label": "Black"},
    {"name": "white", "label": "White"},
    {"name": "off-white", "label": "Off-white"},
]
